### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zzzfo** [nanmi/YOLOX-deepstream#2]
我使用了您的代码来部署我自己训练的yolox模型，在编译以后，运行deepstream_app_config.txt的过程中报了这个错，这是怎么回事？
**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:181>: Pipeline ready

Opening in BLOCKING MODE
Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:167>: Pipeline running

NvMMLiteOpen : Block : BlockType = 4 
===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4 
Segmentation fault (core dumped)

**Comment by nanmi** [comment]
您似乎是pipeline的问题，似乎是encode的问题，请问您是利用deepstream的底层tensorrt来build engine吗？建议单独使用tensorrt build engine。另外推理使用dgpu和jetson的硬件编码器是不一样的，请参考gstreamer API<https://gstreamer.freedesktop.org/documentation/libs.html?gi-language=c>

**Comment by zzzfo** [comment]
> 您似乎是pipeline的问题，似乎是encode的问题，请问您是利用deepstream的底层tensorrt来build engine吗？建议单独使用tensorrt build engine。另外推理使用dgpu和jetson的硬件编码器是不一样的，请参考gstreamer APIhttps://gstreamer.freedesktop.org/documentation/libs.html?gi-language=c

我使用了官方的tensorrt来构建engine,经过测试是可以使用的，但是部署到deepstream上也是报这个Segmentation fault (core dumped)，deepstream出现了黑框，随后退出…这是怎么回事呀

**Comment by geekplusaa** [comment]
> 我使用了您的代码来部署我自己训练的yolox模型，在编译以后，运行deepstream_app_config.txt的过程中报了这个错，这是怎么回事？
> **PERF: FPS 0 (Avg)
> **PERF: 0.00 (0.00)
> ** INFO: <bus_callback:181>: Pipeline ready
> 
> Opening in BLOCKING MODE
> Opening in BLOCKING MODE
> NvMMLiteOpen : Block : BlockType = 261
> NVMEDIA: Reading vendor.tegra.display-size : status: 6
> NvMMLiteBlockCreate : Block : BlockType = 261
> ** INFO: <bus_callback:167>: Pipeline running
> 
> NvMMLiteOpen : Block : BlockType = 4
> ===== NVMEDIA: NVENC =====
> NvMMLiteBlockCreate : Block : BlockType = 4
> Segmentation fault (core dumped)

你好，您编译好的 nvdsparsebbox_yolox.o 文件能分享一下吗？

**Comment by zzzfo** [comment]
> > 我使用了您的代码来部署我自己训练的yolox模型，在编译以后，运行deepstream_app_config.txt的过程中报了这个错，这是怎么回事？
> > **PERF: FPS 0 (Avg)
> > **PERF: 0.00 (0.00)
> > ** INFO: <bus_callback:181>: Pipeline ready
> > Opening in BLOCKING MODE
> > Opening in BLOCKING MODE
> > NvMMLiteOpen : Block : BlockType = 261
> > NVMEDIA: Reading vendor.tegra.display-size : status: 6
> > NvMMLiteBlockCreate : Block : BlockType = 261
> > ** INFO: <bus_callback:167>: Pipeline running
> > NvMMLiteOpen : Block : BlockType = 4
> > ===== NVMEDIA: NVENC =====
> > NvMMLiteBlockCreate : Block : BlockType = 4
> > Segmentation fault (core dumped)
> 
> 你好，您编译好的 nvdsparsebbox_yolox.o 文件能分享一下吗？

可以呀，但是这个文件好像上传不了

**Comment by geekplusaa** [comment]
> > > 我使用了您的代码来部署我自己训练的yolox模型，在编译以后，运行deepstream_app_config.txt的过程中报了这个错，这是怎么回事？
> > > **PERF: FPS 0 (Avg)
> > > **PERF: 0.00 (0.00)
> > > ** INFO: <bus_callback:181>: Pipeline ready
> > > Opening in BLOCKING MODE
> > > Opening in BLOCKING MODE
> > > NvMMLiteOpen : Block : BlockType = 261
> > > NVMEDIA: Reading vendor.tegra.display-size : status: 6
> > > NvMMLiteBlockCreate : Block : BlockType = 261
> > > ** INFO: <bus_callback:167>: Pipeline running
> > > NvMMLiteOpen : Block : BlockType = 4
> > > ===== NVMEDIA: NVENC =====
> > > NvMMLiteBlockCreate : Block : BlockType = 4
> > > Segmentation fault (core dumped)
> > 
> > 
> > 你好，您编译好的 nvdsparsebbox_yolox.o 文件能分享一下吗？
> 
> 可以呀，但是这个文件好像上传不了

麻烦发一下邮箱吧，谢谢了   122716072@qq.com

**Comment by zzzfo** [comment]
> > > > 我使用了您的代码来部署我自己训练的yolox模型，在编译以后，运行deepstream_app_config.txt的过程中报了这个错，这是怎么回事？
> > > > **PERF: FPS 0 (Avg)
> > > > **PERF: 0.00 (0.00)
> > > > ** INFO: <bus_callback:181>: Pipeline ready
> > > > Opening in BLOCKING MODE
> > > > Opening in BLOCKING MODE
> > > > NvMMLiteOpen : Block : BlockType = 261
> > > > NVMEDIA: Reading vendor.tegra.display-size : status: 6
> > > > NvMMLiteBlockCreate : Block : BlockType = 261
> > > > ** INFO: <bus_callback:167>: Pipeline running
> > > > NvMMLiteOpen : Block : BlockType = 4
> > > > ===== NVMEDIA: NVENC =====
> > > > NvMMLiteBlockCreate : Block : BlockType = 4
> > > > Segmentation fault (core dumped)
> > > 
> > > 
> > > 你好，您编译好的 nvdsparsebbox_yolox.o 文件能分享一下吗？
> > 
> > 
> > 可以呀，但是这个文件好像上传不了
> 
> 麻烦发一下邮箱吧，谢谢了 [122716072@qq.com](mailto:122716072@qq.com)
> CUDN 版本 tensorrt版本 是多少啊？

cuda 11.1 
cudnn 8.1.0
tensorrt 7.2.3.4
已发，注意查收！
