### ISSUE TITLE
Installation error in jetson-nano

### ISSUE THREAD

**Issue by zhennronnnhui** [nanmi/YOLOX-deepstream#6]
When I ran:
%cd YOLOX-deepstream/nvdsinfer_custom_impl_yolox/
!make

-------------------------------------

In file included from nvdsparsebbox_yolox.cpp:25:0:
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:375:19: error: ‘IPluginFactory’ in namespace ‘nvcaffeparser1’ does not name a type
   nvcaffeparser1::IPluginFactory *pluginFactory;
                   ^~~~~~~~~~~~~~
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:376:19: error: ‘IPluginFactoryExt’ in namespace ‘nvcaffeparser1’ does not name a type
   nvcaffeparser1::IPluginFactoryExt *pluginFactoryExt;
                   ^~~~~~~~~~~~~~~~~
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:386:16: error: ‘IPluginFactory’ in namespace ‘nvuffparser’ does not name a type
   nvuffparser::IPluginFactory *pluginFactory;
                ^~~~~~~~~~~~~~
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:387:16: error: ‘IPluginFactoryExt’ in namespace ‘nvuffparser’ does not name a type
   nvuffparser::IPluginFactoryExt *pluginFactoryExt;
                ^~~~~~~~~~~~~~~~~
Makefile:47: recipe for target 'nvdsparsebbox_yolox.o' failed
make: *** [nvdsparsebbox_yolox.o] Error 1

**Comment by zhennronnnhui** [comment]
Please help!

**Comment by parthlathiya42** [comment]
Did you get any solution for this??

I'm getting the same type of error.

`nano@nano-desktop:/opt/nvidia/deepstream/deepstream-5.1/sources/yolo$ make -C nvdsinfer_custom_impl_Yolo
make: Entering directory '/opt/nvidia/deepstream/deepstream-5.1/sources/yolo/nvdsinfer_custom_impl_Yolo'
g++ -c  -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream-5.1/sources/includes -I/usr/local/cuda-10.2/include nvdsinfer_yolo_engine.cpp
In file included from nvdsinfer_yolo_engine.cpp:26:0:
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:375:19: error: ‘IPluginFactory’ in namespace ‘nvcaffeparser1’ does not name a type
   nvcaffeparser1::IPluginFactory *pluginFactory;
                   ^~~~~~~~~~~~~~
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:376:19: error: ‘IPluginFactoryExt’ in namespace ‘nvcaffeparser1’ does not name a type
   nvcaffeparser1::IPluginFactoryExt *pluginFactoryExt;
                   ^~~~~~~~~~~~~~~~~
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:386:16: error: ‘IPluginFactory’ in namespace ‘nvuffparser’ does not name a type
   nvuffparser::IPluginFactory *pluginFactory;
                ^~~~~~~~~~~~~~
/opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:387:16: error: ‘IPluginFactoryExt’ in namespace ‘nvuffparser’ does not name a type
   nvuffparser::IPluginFactoryExt *pluginFactoryExt;
                ^~~~~~~~~~~~~~~~~
In file included from nvdsinfer_yolo_engine.cpp:28:0:
yoloPlugins.h:62:17: error: looser throw specifier for ‘virtual const char* YoloLayer::getPluginType() const’
     const char* getPluginType () const override { return YOLOLAYER_PLUGIN_NAME; }
                 ^~~~~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/NvInferLegacyDims.h:53:0,
                 from /usr/include/aarch64-linux-gnu/NvInfer.h:53,
                 from /usr/include/aarch64-linux-gnu/NvCaffeParser.h:53,
                 from /opt/nvidia/deepstream/deepstream-5.1/sources/includes/nvdsinfer_custom_impl.h:128,
                 from nvdsinfer_yolo_engine.cpp:26:

`
and so on...

**Comment by tulbureandreit** [comment]
@Willert98 what kind of board are you using ?
@parthlathiya42 @ronnnhui 

I think the main problem is the fact that you are using deepstream 5.1. Try upgrading to 6 and also your jetpack to 4.6
